objects: [ box1, box2, box3, box4, box5, box6, box7, box8, box9, box10, box11, box12 ]

# type of symmetry that characterizes each object. Used to check multiple
# possible configurations. Can be "none", "cubic", "cylindrical" (TODO), spherical (TODO).
# Note that the meshes used to estimate the object poses must have their
# origin set correctly for this to work. Parts with cubic or spherical symmetry
# must have their origin at the center of the mesh. Parts with cylindrical symmetry
# must have their origin on the central axis and the central axis must align with the z axis of it's coordinate frame00.
object_symmetries: [ cubic, cubic, cubic, cubic, cubic, cubic, cubic, cubic, cubic, cubic, cubic, cubic ]

number_of_checks: 1

margin: [0.001, 0.001, 0.001, 1.1, 0.1, 0.1, 0.1] #0.01->slightly over 10 degree difference

number_of_tasks: 3

task1:
  name: castle
  number_of_connections: 12
  connection1:
    parts: [1, 2] #1 based
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1] #part2.x = part1.x + 0.025
  connection2:
    parts: [2, 3]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection3:
    parts: [3, 4]
    relative_pose: [0, 0, -0.025, 0, 0, 0, 1]
  connection4:
    parts: [4, 5]
    relative_pose: [0, 0, -0.025, 0, 0, 0, 1]
  connection5:
    parts: [1, 8]
    relative_pose: [0, 0, -0.025, 0, 0, 0, 1]
  connection6:
    parts: [8, 7]
    relative_pose: [0, 0, -0.025, 0, 0, 0, 1]
  connection7:
    parts: [7, 6]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection8:
    parts: [6, 5]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection9:
    parts: [9, 1]
    relative_pose: [0, 0.025, 0, 0, 0, 0, 1]
  connection10:
    parts: [10, 3]
    relative_pose: [0, 0.025, 0, 0, 0, 0, 1]
  connection11:
    parts: [11, 5]
    relative_pose: [0, 0.025, 0, 0, 0, 0, 1]
  connection12:
    parts: [12, 7]
    relative_pose: [0, 0.025, 0, 0, 0, 0, 1]
task2:  
  name: rail
  number_of_connections: 12
  connection1:
    parts: [1, 2]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection2:
    parts: [2, 3]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection3:
    parts: [3, 4]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection4:
    parts: [4, 5]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection5:
    parts: [2, 6]
    relative_pose: [0, 0, -0.025, 0, 0, 0, 1]
  connection6:
    parts: [4, 7]
    relative_pose: [0, 0, -0.025, 0, 0, 0, 1]
  connection7:
    parts: [6, 9]
    relative_pose: [0, 0, -0.025, 0, 0, 0, 1]
  connection8:
    parts: [7, 11]
    relative_pose: [0, 0, -0.025, 0, 0, 0, 1]
  connection9:
    parts: [8, 9]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection10:
    parts: [9, 10]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection11:
    parts: [10, 11]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection12:
    parts: [11, 12]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
task3:
  name: tower
  number_of_connections: 18
  connection1:
    parts: [1, 2]
    relative_pose: [-0.0125, 0.025, 0, 0, 0, 0, 1]
  connection2:
    parts: [1, 3]
    relative_pose: [0.0125, 0.025, 0, 0, 0, 0, 1]
  connection3:
    parts: [2, 3]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection4:
    parts: [2, 4]
    relative_pose: [-0.0125, 0.025, 0, 0, 0, 0, 1]
  connection5:
    parts: [2, 5]
    relative_pose: [0.0125, 0.025, 0, 0, 0, 0, 1]
  connection6:
    parts: [4, 5]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection7:
    parts: [3, 5]
    relative_pose: [-0.0125, 0.025, 0, 0, 0, 0, 1]
  connection8:
    parts: [3, 6]
    relative_pose: [0.0125, 0.025, 0, 0, 0, 0, 1]
  connection9:
    parts: [5, 6]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection10:
    parts: [4, 7]
    relative_pose: [-0.0125, 0.025, 0, 0, 0, 0, 1]
  connection11:
    parts: [4, 8]
    relative_pose: [0.0125, 0.025, 0, 0, 0, 0, 1]
  connection12:
    parts: [7, 8]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection13:
    parts: [5, 8]
    relative_pose: [-0.0125, 0.025, 0, 0, 0, 0, 1]
  connection14:
    parts: [5, 9]
    relative_pose: [0.0125, 0.025, 0, 0, 0, 0, 1]
  connection15:
    parts: [8, 9]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
  connection16:
    parts: [6, 9]
    relative_pose: [-0.0125, 0.025, 0, 0, 0, 0, 1]
  connection17:
    parts: [6, 10]
    relative_pose: [0.0125, 0.025, 0, 0, 0, 0, 1]
  connection18:
    parts: [9, 10]
    relative_pose: [0.025, 0, 0, 0, 0, 0, 1]
